import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CheckCircle, FileDown, MessageSquare, PlayCircle } from "lucide-react";
import { useAuth } from "@/lib/auth";
import { supabase } from "@/integrations/supabase/client";
export const Route = createFileRoute("/learning")({ component: LearningPage });
function LearningPage() {
  const { user } = useAuth(); const [progress, setProgress] = useState(0); const [answer, setAnswer] = useState(""); const [discussion, setDiscussion] = useState("");
  async function saveProgress(value: number) { setProgress(value); if (user) await (supabase as any).from("course_progress").upsert({ user_id: user.id, product_id: "00000000-0000-0000-0000-000000000000", lesson_id: "demo", progress: value, completed_at: value === 100 ? new Date().toISOString() : null }); }
  return <div className="mx-auto max-w-5xl px-4 py-14"><h1 className="text-3xl font-bold">مساحة التعلم</h1><p className="mt-2 text-muted-foreground">مشغل فيديو جاهز للربط بتخزين خاص، مع حفظ التقدم والاختبارات.</p><div className="mt-8 aspect-video rounded-2xl bg-slate-950 p-6 text-center text-white"><PlayCircle className="mx-auto mt-16 h-16 w-16 text-primary"/><p className="mt-3">Video player placeholder — أضف رابط الفيديو الموقّع من الخادم</p></div><div className="mt-4"><div className="mb-2 flex justify-between text-sm"><span>تقدم الدرس</span><span>{progress}%</span></div><div className="h-3 rounded-full bg-muted"><div className="h-3 rounded-full bg-primary transition-all" style={{ width: `${progress}%` }}/></div><input className="mt-3 w-full" type="range" value={progress} onChange={e => saveProgress(Number(e.target.value))}/></div><section className="mt-10 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border p-5"><h2 className="flex items-center gap-2 font-bold"><CheckCircle className="h-5 w-5 text-primary"/>اختبار قصير</h2><p className="mt-4">ما أفضل ممارسة لحماية ملفات الفيديو؟</p><label className="mt-3 block"><input type="radio" name="q" value="signed" onChange={e => setAnswer(e.target.value)}/> روابط موقعة قصيرة</label><label className="mt-2 block"><input type="radio" name="q" value="public" onChange={e => setAnswer(e.target.value)}/> رابط عام دائم</label><p className="mt-3 text-sm">{answer && (answer === "signed" ? "إجابة صحيحة" : "حاول مرة أخرى")}</p></div><div className="rounded-2xl border p-5"><h2 className="flex items-center gap-2 font-bold"><MessageSquare className="h-5 w-5 text-primary"/>مناقشة الدرس</h2><textarea value={discussion} onChange={e => setDiscussion(e.target.value)} className="mt-4 min-h-24 w-full rounded-lg border p-3" placeholder="اكتب سؤالك"/><button onClick={() => { if (user && discussion) (supabase as any).from("lesson_discussions").insert({ product_id: "00000000-0000-0000-0000-000000000000", lesson_id: "demo", user_id: user.id, body: discussion }); setDiscussion(""); }} className="mt-2 rounded-lg bg-primary px-4 py-2 text-primary-foreground">نشر</button></div></section><button onClick={() => window.print()} className="mt-8 inline-flex items-center gap-2 rounded-xl border px-4 py-2"><FileDown className="h-4 w-4"/>طباعة شهادة الإتمام</button></div>;
}
