/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAffiliateClickRouteImport } from './routes/api.affiliate-click'
import { Route as ApiAffiliateConversionRouteImport } from './routes/api.affiliate-conversion'
import { Route as ApiAffiliateReferralRouteImport } from './routes/api.affiliate-referral'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiDownloadRouteImport } from './routes/api.download'
import { Route as ApiPaymentWebhooksRouteImport } from './routes/api.payment-webhooks'
import { Route as ApiPaymentsRouteImport } from './routes/api.payments'
import { Route as ApiPayoutsRouteImport } from './routes/api.payouts'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateClickRoute = ApiAffiliateClickRouteImport.update({
  id: '/api/affiliate-click',
  path: '/api/affiliate-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateConversionRoute = ApiAffiliateConversionRouteImport.update({
  id: '/api/affiliate-conversion',
  path: '/api/affiliate-conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateReferralRoute = ApiAffiliateReferralRouteImport.update({
  id: '/api/affiliate-referral',
  path: '/api/affiliate-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadRoute = ApiDownloadRouteImport.update({
  id: '/api/download',
  path: '/api/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhooksRoute = ApiPaymentWebhooksRouteImport.update({
  id: '/api/payment-webhooks',
  path: '/api/payment-webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsRoute = ApiPaymentsRouteImport.update({
  id: '/api/payments',
  path: '/api/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayoutsRoute = ApiPayoutsRouteImport.update({
  id: '/api/payouts',
  path: '/api/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/cookies': typeof CookiesRoute
  '/courses': typeof CoursesRoute
  '/favorites': typeof FavoritesRoute
  '/learning': typeof LearningRoute
  '/membership': typeof MembershipRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/seller': typeof SellerRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/api/affiliate-click': typeof ApiAffiliateClickRoute
  '/api/affiliate-conversion': typeof ApiAffiliateConversionRoute
  '/api/affiliate-referral': typeof ApiAffiliateReferralRoute
  '/api/chat': typeof ApiChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/payment-webhooks': typeof ApiPaymentWebhooksRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/payouts': typeof ApiPayoutsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/cookies': typeof CookiesRoute
  '/courses': typeof CoursesRoute
  '/favorites': typeof FavoritesRoute
  '/learning': typeof LearningRoute
  '/membership': typeof MembershipRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/seller': typeof SellerRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/api/affiliate-click': typeof ApiAffiliateClickRoute
  '/api/affiliate-conversion': typeof ApiAffiliateConversionRoute
  '/api/affiliate-referral': typeof ApiAffiliateReferralRoute
  '/api/chat': typeof ApiChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/payment-webhooks': typeof ApiPaymentWebhooksRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/payouts': typeof ApiPayoutsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/cookies': typeof CookiesRoute
  '/courses': typeof CoursesRoute
  '/favorites': typeof FavoritesRoute
  '/learning': typeof LearningRoute
  '/membership': typeof MembershipRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/refunds': typeof RefundsRoute
  '/seller': typeof SellerRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/api/affiliate-click': typeof ApiAffiliateClickRoute
  '/api/affiliate-conversion': typeof ApiAffiliateConversionRoute
  '/api/affiliate-referral': typeof ApiAffiliateReferralRoute
  '/api/chat': typeof ApiChatRoute
  '/api/download': typeof ApiDownloadRoute
  '/api/payment-webhooks': typeof ApiPaymentWebhooksRoute
  '/api/payments': typeof ApiPaymentsRoute
  '/api/payouts': typeof ApiPayoutsRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/content'
    | '/cookies'
    | '/courses'
    | '/favorites'
    | '/learning'
    | '/membership'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/seller'
    | '/store'
    | '/terms'
    | '/api/affiliate-click'
    | '/api/affiliate-conversion'
    | '/api/affiliate-referral'
    | '/api/chat'
    | '/api/download'
    | '/api/payment-webhooks'
    | '/api/payments'
    | '/api/payouts'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/content'
    | '/cookies'
    | '/courses'
    | '/favorites'
    | '/learning'
    | '/membership'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/seller'
    | '/store'
    | '/terms'
    | '/api/affiliate-click'
    | '/api/affiliate-conversion'
    | '/api/affiliate-referral'
    | '/api/chat'
    | '/api/download'
    | '/api/payment-webhooks'
    | '/api/payments'
    | '/api/payouts'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliate'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/content'
    | '/cookies'
    | '/courses'
    | '/favorites'
    | '/learning'
    | '/membership'
    | '/messages'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/purchases'
    | '/refunds'
    | '/seller'
    | '/store'
    | '/terms'
    | '/api/affiliate-click'
    | '/api/affiliate-conversion'
    | '/api/affiliate-referral'
    | '/api/chat'
    | '/api/download'
    | '/api/payment-webhooks'
    | '/api/payments'
    | '/api/payouts'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRoute
  CookiesRoute: typeof CookiesRoute
  CoursesRoute: typeof CoursesRoute
  FavoritesRoute: typeof FavoritesRoute
  LearningRoute: typeof LearningRoute
  MembershipRoute: typeof MembershipRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  RefundsRoute: typeof RefundsRoute
  SellerRoute: typeof SellerRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  ApiAffiliateClickRoute: typeof ApiAffiliateClickRoute
  ApiAffiliateConversionRoute: typeof ApiAffiliateConversionRoute
  ApiAffiliateReferralRoute: typeof ApiAffiliateReferralRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDownloadRoute: typeof ApiDownloadRoute
  ApiPaymentWebhooksRoute: typeof ApiPaymentWebhooksRoute
  ApiPaymentsRoute: typeof ApiPaymentsRoute
  ApiPayoutsRoute: typeof ApiPayoutsRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate-click': {
      id: '/api/affiliate-click'
      path: '/api/affiliate-click'
      fullPath: '/api/affiliate-click'
      preLoaderRoute: typeof ApiAffiliateClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate-conversion': {
      id: '/api/affiliate-conversion'
      path: '/api/affiliate-conversion'
      fullPath: '/api/affiliate-conversion'
      preLoaderRoute: typeof ApiAffiliateConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate-referral': {
      id: '/api/affiliate-referral'
      path: '/api/affiliate-referral'
      fullPath: '/api/affiliate-referral'
      preLoaderRoute: typeof ApiAffiliateReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download': {
      id: '/api/download'
      path: '/api/download'
      fullPath: '/api/download'
      preLoaderRoute: typeof ApiDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment-webhooks': {
      id: '/api/payment-webhooks'
      path: '/api/payment-webhooks'
      fullPath: '/api/payment-webhooks'
      preLoaderRoute: typeof ApiPaymentWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments': {
      id: '/api/payments'
      path: '/api/payments'
      fullPath: '/api/payments'
      preLoaderRoute: typeof ApiPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payouts': {
      id: '/api/payouts'
      path: '/api/payouts'
      fullPath: '/api/payouts'
      preLoaderRoute: typeof ApiPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRoute,
  CookiesRoute: CookiesRoute,
  CoursesRoute: CoursesRoute,
  FavoritesRoute: FavoritesRoute,
  LearningRoute: LearningRoute,
  MembershipRoute: MembershipRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  RefundsRoute: RefundsRoute,
  SellerRoute: SellerRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  ApiAffiliateClickRoute: ApiAffiliateClickRoute,
  ApiAffiliateConversionRoute: ApiAffiliateConversionRoute,
  ApiAffiliateReferralRoute: ApiAffiliateReferralRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDownloadRoute: ApiDownloadRoute,
  ApiPaymentWebhooksRoute: ApiPaymentWebhooksRoute,
  ApiPaymentsRoute: ApiPaymentsRoute,
  ApiPayoutsRoute: ApiPayoutsRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
