create table if not exists public.products (id uuid primary key default gen_random_uuid(), slug text unique not null, title text not null, description text not null, long_description text not null, price numeric not null, old_price numeric, type text not null default 'digital', features jsonb not null default '[]', curriculum jsonb not null default '[]', badge text, meta text, instructor text, rating numeric not null default 0, students integer not null default 0, image_url text, created_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, phone text, avatar_url text, updated_at timestamptz default now());
create table if not exists public.chat_messages (id uuid primary key default gen_random_uuid(), user_id uuid references auth.users(id) on delete set null, role text not null, content text not null, created_at timestamptz default now());
alter table public.products enable row level security; alter table public.profiles enable row level security; alter table public.chat_messages enable row level security;
create policy "products public read" on public.products for select using (true);
create policy "admin manage products" on public.products for all to authenticated using ((auth.jwt()->>'email') = 'memoskaf@gmail.com') with check ((auth.jwt()->>'email') = 'memoskaf@gmail.com');
create policy "own profile" on public.profiles for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);
create policy "own chat" on public.chat_messages for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into public.products (slug, title, description, long_description, price, old_price, type, features, curriculum, badge, meta, instructor, rating, students, image_url)
values
  ('notion-productivity-pack', 'حزمة قوالب Notion للإنتاجية', 'نظام متكامل لإدارة المهام والأهداف والمشاريع داخل Notion.', 'حزمة قوالب عملية جاهزة للاستخدام مع دليل مصور.', 29, 49, 'digital', '["أكثر من 12 قالبًا", "تحديثات مجانية", "دليل استخدام"]', '[{"title":"لوحة التحكم الرئيسية","duration":"قالب"},{"title":"إدارة المهام اليومية","duration":"قالب"}]', 'الأكثر مبيعًا', 'تحميل فوري', 'فريق جود', 4.9, 1840, 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80'),
  ('digital-marketing-course', 'كورس التسويق الرقمي الشامل', 'من الصفر إلى الاحتراف في الإعلانات وتحليل البيانات.', 'كورس عملي لبناء الحملات وقياس النتائج وتحسين المبيعات.', 199, 299, 'course', '["40 ساعة تدريبية", "شهادة إتمام", "دعم للطلاب"]', '[{"title":"مقدمة في التسويق الرقمي","duration":"4 ساعات"},{"title":"إعلانات ميتا","duration":"10 ساعات"}]', 'خصم 33%', '40+ ساعة', 'م. سارة الحسن', 4.8, 3120, 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=900&q=80'),
  ('ecommerce-ebook', 'كتاب أساسيات التجارة الإلكترونية', 'دليل عملي لبناء متجرك الإلكتروني الأول.', 'كتاب مركز يشرح اختيار المنتج والتسعير وأول حملة تسويقية.', 15, null, 'digital', '["180 صفحة", "قوالب جداول", "PDF وEPUB"]', '[{"title":"اختيار المنتج","duration":"فصل"},{"title":"التسعير والربحية","duration":"فصل"}]', null, 'PDF + EPUB', 'أ. خالد منصور', 4.7, 960, 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=80'),
  ('figma-ui-course', 'كورس احتراف التصميم بـ Figma', 'تعلّم تصميم الواجهات وبناء أنظمة تصميم كاملة.', 'من أساسيات Figma حتى تسليم نظام تصميم متكامل.', 149, null, 'course', '["مشاريع عملية", "ملفات عمل", "شهادة إتمام"]', '[{"title":"أساسيات Figma","duration":"5 ساعات"},{"title":"المكونات والمتغيرات","duration":"7 ساعات"}]', null, '25 ساعة', 'م. ليان عبد الله', 4.9, 1470, 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?auto=format&fit=crop&w=900&q=80'),
  ('arabic-icons-pack', 'حزمة أيقونات عربية', 'مكتبة أيقونات SVG عالية الجودة للواجهات العربية.', 'أيقونات موحدة الأسلوب بصيغة SVG وملف Figma منظم.', 39, null, 'digital', '["500+ أيقونة", "ترخيص تجاري", "ملفات Figma"]', '[{"title":"أيقونات الواجهة","duration":"180 أيقونة"},{"title":"أيقونات الدفع","duration":"120 أيقونة"}]', null, 'SVG + Figma', 'استوديو نقش', 4.6, 720, 'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=900&q=80'),
  ('python-beginners-course', 'كورس Python للمبتدئين', 'ابدأ البرمجة بمشاريع تطبيقية خطوة بخطوة.', 'كورس يبدأ من الصفر وينتهي بمشاريع عملية في Python.', 99, 149, 'course', '["لا يتطلب خبرة", "10 مشاريع", "دعم مباشر"]', '[{"title":"أساسيات اللغة","duration":"6 ساعات"},{"title":"مشاريع تطبيقية","duration":"8 ساعات"}]', null, '30 ساعة', 'م. عمر الديب', 4.8, 2510, 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80')
on conflict (slug) do nothing;
